"""
Meta-NetBox Data Source Adapter for Handbook Generator

Author: Andreas Huemmer [andreas.huemmer@adminsend.de]
Copyright: 2025
"""

from typing import Optional
from src.data_source_adapter import DataSourceAdapter


class MetaNetBoxAdapter(DataSourceAdapter):
    """
    Meta-NetBox data source adapter for NetBox metadata.
    
    Provides access to NetBox metadata loaded from metadata-netbox.yaml file.
    This file is generated by NetBoxMetadataLoader and contains contacts,
    devices, and sites fetched from NetBox.
    
    Example usage:
        netbox_metadata = {
            'contacts': {
                'ciso': {'name': 'John Doe', 'email': 'john@example.com'},
                'cio': {'name': 'Jane Smith', 'email': 'jane@example.com'}
            },
            'devices': {
                'firewall': {'name': 'fw-01', 'ip': '192.168.1.1'}
            },
            'sites': {
                'primary': {'name': 'HQ', 'address': '123 Main St'}
            }
        }
        adapter = MetaNetBoxAdapter(netbox_metadata)
        adapter.connect()
        ciso_name = adapter.get_field("contacts.ciso.name")
        firewall_name = adapter.get_field("devices.firewall.name")
        adapter.disconnect()
    """
    
    def __init__(self, netbox_metadata: dict):
        """
        Initialize Meta-NetBox adapter with NetBox metadata.
        
        Args:
            netbox_metadata: Dictionary with NetBox metadata from metadata-netbox.yaml
        """
        self.netbox_metadata = netbox_metadata or {}
        self._connected = False
    
    def connect(self) -> bool:
        """
        Validate NetBox metadata (no external connection needed).
        
        Returns:
            True if metadata is valid, False otherwise
        """
        if self.netbox_metadata is None:
            return False
        
        # Validate that metadata is a dictionary
        if not isinstance(self.netbox_metadata, dict):
            return False
        
        self._connected = True
        return True
    
    def disconnect(self) -> None:
        """
        No-op for meta-netbox adapter (no external connection to close).
        """
        self._connected = False
    
    def get_field(self, field_path: str) -> Optional[str]:
        """
        Retrieve field value from NetBox metadata.
        
        Supports dot-notation field paths:
        - "contacts.ciso.name" -> netbox_metadata['contacts']['ciso']['name']
        - "contacts.ciso.email" -> netbox_metadata['contacts']['ciso']['email']
        - "devices.firewall.name" -> netbox_metadata['devices']['firewall']['name']
        - "sites.primary.name" -> netbox_metadata['sites']['primary']['name']
        
        Args:
            field_path: Dot-separated path to the field
            
        Returns:
            Field value as string, or None if field not found
            
        Raises:
            ConnectionError: If not connected (metadata not validated)
            ValueError: If field_path is invalid
        """
        if not self._connected:
            raise ConnectionError("Not connected to NetBox metadata. Call connect() first.")
        
        if not field_path:
            raise ValueError("field_path cannot be empty")
        
        return self._resolve_field_path(field_path)
    
    def _resolve_field_path(self, field_path: str) -> Optional[str]:
        """
        Resolve dot-notation field path to NetBox metadata value.
        
        Args:
            field_path: Dot-separated field path
            
        Returns:
            Field value as string, or None if not found
        """
        parts = field_path.split('.')
        current = self.netbox_metadata
        
        try:
            for part in parts:
                if isinstance(current, dict):
                    if part in current:
                        current = current[part]
                    else:
                        return None
                else:
                    return None
            
            # Convert final value to string
            if current is not None:
                return str(current)
            return None
            
        except (KeyError, TypeError, AttributeError):
            return None
